# Database configuration sqlite
db.type=sqlite
db.url=jdbc:sqlite:/home/ricardo/Documentos/data/tsp.db
db.user=
db.password=

# Database configuration postgres
# db.type=postgres
# db.url=jdbc:postgresql://localhost:5432/tsp?currentSchema=tsp
# db.user=tsp_user
# db.password=tu_password