# Parametros de ejemplos - No deben tomarse como parametros serios de optimizacion
heuristic.initial-temperature=0.1
heuristic.temperature-epsilon=0.000001
heuristic.cooling-factor=0.9
heuristic.batch-size=20
heuristic.max-attempts-per-batch=200
heuristic.seed=123