# ==========================================================
# Control general del experimento
# ==========================================================

experiment.generations=
experiment.candidates-per-generation=
experiment.seeds=


# ==========================================================
# Espacio de búsqueda: Threshold Accepting
# ==========================================================

experiment.cooling-factor.min=
experiment.cooling-factor.max=

experiment.temperature-epsilon.min=
experiment.temperature-epsilon.max=

experiment.batch-size.min=
experiment.batch-size.max=

experiment.max-attempt-factor.min=
experiment.max-attempt-factor.max=


# ==========================================================
# Cálculo de temperatura inicial
# ==========================================================

experiment.initial-temperature.guess=

experiment.target-acceptance.min=
experiment.target-acceptance.max=

experiment.acceptance-epsilon=
experiment.temperature-samples=
experiment.temperature-max-iterations=


# ==========================================================
# Evolución de parámetros
# ==========================================================

experiment.exploration-probability=
experiment.variation-factor=

experiment.parameter-seed=