# ==========================================================
# Control general del experimento TSP 40
# ==========================================================

experiment.generations=3
experiment.candidates-per-generation=5
experiment.seeds=131321,131347,131389,131415,131442,131468,131503,131527,131561,131599,123,456,658,789,2026,101112,131415,161803,271828,314159,424242,8675309


# ==========================================================
# Espacio de búsqueda: Threshold Accepting
# ==========================================================

experiment.cooling-factor.min=0.95
experiment.cooling-factor.max=0.9975

experiment.temperature-epsilon.min=0.0000001
experiment.temperature-epsilon.max=0.000001

experiment.batch-size.min=4000
experiment.batch-size.max=5000

experiment.max-attempt-factor.min=45
experiment.max-attempt-factor.max=80


# ==========================================================
# Cálculo de temperatura inicial
# ==========================================================

experiment.initial-temperature.guess=1.0

experiment.target-acceptance.min=0.87
experiment.target-acceptance.max=0.93

experiment.acceptance-epsilon=0.0025
experiment.temperature-samples=4000
experiment.temperature-max-iterations=150


# ==========================================================
# Evolución de parámetros
# ==========================================================

experiment.exploration-probability=0.30
experiment.variation-factor=0.12

experiment.parameter-seed=20260911