heuristic.initial-temperature=110592
heuristic.temperature-epsilon=8.550680998281418E-7
heuristic.cooling-factor=0.985
heuristic.batch-size=976
heuristic.max-attempts-per-batch=43920
heuristic.seed=262831